
[project]
name = "ewe"
version = "0.1.0"
description = "Easy WiFi Extender for Linux"
readme = "README.md"
authors = [{ name = "PauWol", email = "paul22wof@proton.me" }]
requires-python = ">=3.11"
dependencies = [
    "cyclopts>=4.22.5",
    "pyroute2>=0.9.6",
    "python-dotenv>=1.2.2",
    "typing-extensions>=4.16.0",
]

[project.scripts]
ewe = "ewe.cli:main"

[tool.hatch.build.targets.wheel]
packages = ["src/ewe"]

[build-system]
requires = ["uv_build>=0.12.3,<0.13.0"]
build-backend = "uv_build"
